### PR TITLE
initial meson build support, compilation fixes, #define/macro fixes

### PR DESCRIPTION
**Pull request by garfunkel**
This PR:
* Meson build system support for portable compilation
* build fixes, #include fixes
* #define fixes, modernisation
* move .big assets into an assets directory and create build targets for them

Eventually I'd like to remove autotools/automake and have VS and XCode build files generated from meson, so that one system controls all the build configs for all supported systems. First, todo:
* translation support in build
* wasm build
* Windows build
* Possibly some mac fixes
* ARM Mac I think is broken (unrelated to meson build)

### CODE REVIEW

**Comment by rbrune** [comment]
Hi garfunkel!
First of all, awesome work. It was on my todo list to modernize the build system.
Any chance you can join the discord to synchronize the efforts. Especially that switching around with defines and the other PR touching assembly stuff is delicate business. Ideally we try to get rid off of most platform dependent stuff. The WASM build is the foundation of that and works without any inline assembly and we should update the other platforms to the same generic ETG system that is now working.

**Comment by garfunkel** [comment]
Sure thing - I tried to join but Discord is saying the link is invalid:

> This invite may be expired, or you might not have permission to join.

**Comment by rbrune** [comment]
Weird!

https://discord.gg/3hTsAsargq

Does this link work?

**Comment by garfunkel** [comment]
Yep - there we go - I'm in.

**Comment by ThibaultLemaire** [comment]
Successfully cherry-picked onto [Tenhauser Gate](https://gitlab.com/homeworldsdl/TenhauserGate/-/commit/2fe7d53d69f0e41d8162e3b5c5f7ae7d4c0f4af3) for building on Linux

**Pull request closed without merging**
